import ngrams.TimeSeries;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static com.google.common.truth.Truth.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Unit Tests for the TimeSeries class.
 *  @author Josh Hug
 */
public class TimeSeriesTest {
    @Test
    public void testFromSpec() {
        TimeSeries catPopulation = new TimeSeries();
        catPopulation.put(1991, 0.0);
        catPopulation.put(1992, 100.0);
        catPopulation.put(1994, 200.0);

        TimeSeries dogPopulation = new TimeSeries();
        dogPopulation.put(1994, 400.0);
        dogPopulation.put(1995, 500.0);

        TimeSeries totalPopulation = catPopulation.plus(dogPopulation);
        // expected: 1991: 0,
        //           1992: 100
        //           1994: 600
        //           1995: 500

        List<Integer> expectedYears = new ArrayList<>
                (Arrays.asList(1991, 1992, 1994, 1995));

        assertThat(totalPopulation.years()).isEqualTo(expectedYears);

        List<Double> expectedTotal = new ArrayList<>
                (Arrays.asList(0.0, 100.0, 600.0, 500.0));

        for (int i = 0; i < expectedTotal.size(); i += 1) {
            assertThat(totalPopulation.data().get(i)).isWithin(1E-10).of(expectedTotal.get(i));
        }
    }

    @Test
    public void testEmptyBasic() {
        TimeSeries catPopulation = new TimeSeries();
        TimeSeries dogPopulation = new TimeSeries();

        assertThat(catPopulation.years()).isEmpty();
        assertThat(catPopulation.data()).isEmpty();

        TimeSeries totalPopulation = catPopulation.plus(dogPopulation);

        assertThat(totalPopulation.years()).isEmpty();
        assertThat(totalPopulation.data()).isEmpty();
    }
    /**
     * below are tests generated by AI 
     * based on the basic test and the method descriptions
     */
    private TimeSeries ts1;
    private TimeSeries ts2;
    private TimeSeries emptyTs;

    @BeforeEach
    void setup(){
        ts1 = new TimeSeries();
        ts1.put(1990, 100.0);
        ts1.put(1992, 200.0);
        ts1.put(1994, 300.0);

        ts2 = new TimeSeries();
        ts2.put(1992, 150.0);
        ts2.put(1994, 250.0);
        ts2.put(1996, 400.0);

        emptyTs = new TimeSeries();
    }

    @Test
    void testDefaultConstructor() {
        TimeSeries ts = new TimeSeries();
        assertTrue(ts.isEmpty());
        assertEquals(0, ts.size());
    }

    @Test
    void testRangeConstructor() {
        // 空 TimeSeries 实例
        emptyTs = new TimeSeries();
        // 1. 筛选部分年份（1991-1993 范围内仅 1992）
        TimeSeries rangeTs = new TimeSeries(ts1, 1991, 1993);
        assertEquals(1, rangeTs.size());
        assertTrue(rangeTs.containsKey(1992));
        assertEquals(200.0, rangeTs.get(1992), 1e-10);
        assertFalse(rangeTs.containsKey(1990)); // 小于 startYear
        assertFalse(rangeTs.containsKey(1994)); // 大于 endYear

        // 2. 包含所有年份（1990-1994）
        TimeSeries fullRangeTs = new TimeSeries(ts1, 1990, 1994);
        assertEquals(ts1.size(), fullRangeTs.size());
        assertTrue(fullRangeTs.containsKey(1990) && fullRangeTs.containsKey(1994));

        // 3. 无匹配年份（2000-2020）
        TimeSeries noMatchTs = new TimeSeries(ts1, 2000, 2020);
        assertTrue(noMatchTs.isEmpty());

        // 4. 边界值（startYear = endYear = 1994）
        TimeSeries singleYearTs = new TimeSeries(ts2, 1994, 1994);
        assertEquals(1, singleYearTs.size());
        assertEquals(250.0, singleYearTs.get(1994), 1e-10);

        // 5. 基于空 TimeSeries 构造
        TimeSeries emptyRangeTs = new TimeSeries(emptyTs, 1990, 2000);
        assertTrue(emptyRangeTs.isEmpty());
    }

    @Test
    void testYears() {
        // 非空情况：TreeMap 按键升序排列（1990, 1992, 1994）
        List<Integer> expectedTs1Years = Arrays.asList(1990, 1992, 1994);
        List<Integer> actualTs1Years = ts1.years();
        assertEquals(expectedTs1Years.size(), actualTs1Years.size());
        assertEquals(expectedTs1Years, actualTs1Years); // 验证顺序和内容

        // 空情况
        assertTrue(emptyTs.years().isEmpty());
    }

     @Test
    void testData() {
        // 非空情况：数据与年份一一对应
        List<Double> expectedTs1Data = Arrays.asList(100.0, 200.0, 300.0);
        List<Double> actualTs1Data = ts1.data();
        assertEquals(expectedTs1Data.size(), actualTs1Data.size());
        for (int i = 0; i < expectedTs1Data.size(); i++) {
            assertEquals(expectedTs1Data.get(i), actualTs1Data.get(i), 1e-10);
        }

        // 空情况
        assertTrue(emptyTs.data().isEmpty());
    }

    @Test
    void testPlus() {
        // 1. 正常求和（含重叠和非重叠年份）
        TimeSeries sumTs = ts1.plus(ts2);
        List<Integer> expectedYears = Arrays.asList(1990, 1992, 1994, 1996);
        assertEquals(expectedYears, sumTs.years()); // 验证年份
        // 验证数据
        assertEquals(100.0, sumTs.get(1990), 1e-10);    // 仅 ts1 有
        assertEquals(350.0, sumTs.get(1992), 1e-10);    // 200 + 150
        assertEquals(550.0, sumTs.get(1994), 1e-10);    // 300 + 250
        assertEquals(400.0, sumTs.get(1996), 1e-10);    // 仅 ts2 有

        // 2. 原实例未被修改
        assertEquals(3, ts1.size());
        assertEquals(3, ts2.size());

        // 3. 与空实例求和
        TimeSeries sumWithEmpty = ts1.plus(emptyTs);
        assertEquals(ts1.years(), sumWithEmpty.years());
        assertEquals(ts1.data(), sumWithEmpty.data());

        // 4. 两个空实例求和
        TimeSeries emptySum = emptyTs.plus(emptyTs);
        assertTrue(emptySum.isEmpty());
    }

    @Test
    void testDividedBy() {
        // 确保 ts2 包含 ts1 所有年份（避免提前异常）
        ts2.put(1990, 50.0);

        // 1. 正常除法（分母有额外年份被忽略）
        TimeSeries divTs = ts1.dividedBy(ts2);
        List<Integer> expectedYears = Arrays.asList(1990, 1992, 1994);
        assertEquals(expectedYears, divTs.years()); // 仅保留分子的年份
        // 验证结果
        assertEquals(2.0, divTs.get(1990), 1e-10);         // 100 / 50
        assertEquals(1.3333333333, divTs.get(1992), 1e-10); // 200 / 150
        assertEquals(1.2, divTs.get(1994), 1e-10);         // 300 / 250

        // 2. 分母缺失分子的年份→抛异常
        ts2.remove(1990); // 移除 ts1 存在的 1990
        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> ts1.dividedBy(ts2)
        );
        assertNotNull(exception); // 确认异常被抛出

        // 3. 分子为空→返回空
        TimeSeries emptyDiv = emptyTs.dividedBy(ts2);
        assertTrue(emptyDiv.isEmpty());

        // 4. 原实例未被修改
        assertEquals(3, ts1.size());
        assertEquals(3, ts2.size());
    }

}  